apiVersion: v1
kind: ConfigMap
metadata:
  name: urlshortener-config
  namespace: urlshortener
data:
  GO_SERVICE_URL: "http://go-service:8000"
  NODE_SERVICE_URL: "http://node-service:3000"
  PYTHON_SERVICE_URL: "http://python-service:5000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  APP_ENV: "production"