name: URL Shortener CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Go Service
        run: docker build -t go-service ./go-service

      - name: Build Node Service
        run: docker build -t node-service ./node-service

      - name: Build Python Service
        run: docker build -t python-service ./python-service